import type { CodeProject } from "@/domain/entities/code-project";

const GITHUB_USER = "HasnathJami";
const repoUrl = (repo: string) => `https://github.com/${GITHUB_USER}/${repo}`;

/**
 * A curated slice of 84 public repositories — the ones that best show how I
 * structure Android, cross-platform and backend code.
 */
export const CODE_PROJECTS: readonly CodeProject[] = [
  // ── Android & Compose ──────────────────────────────────────────────────
  {
    id: "quotegram",
    repo: "Quotegram",
    title: "Quotegram",
    description:
      "A Jetpack Compose quotes app wired end to end — Hilt DI, Room caching, Retrofit networking and a Coroutines/Flow reactive layer behind a typed navigation graph.",
    url: repoUrl("Quotegram"),
    language: "Kotlin",
    topics: ["jetpack-compose", "mvvm", "hilt", "room", "retrofit2", "flow"],
    stars: 1,
    forks: 0,
    category: "android",
    featured: true,
  },
  {
    id: "news-horizon",
    repo: "NewsHorizon",
    title: "NewsHorizon",
    description:
      "A smart news reader built on MVI with Coroutines and Flow, Paging 3 for infinite feeds, Room for offline reading and DataStore for user preferences.",
    url: repoUrl("NewsHorizon"),
    language: "Kotlin",
    topics: ["jetpack-compose", "mvi", "paging3", "room", "datastore", "hilt"],
    stars: 0,
    forks: 0,
    category: "android",
    featured: true,
  },
  {
    id: "quickgrab-superapp",
    repo: "QuickGrab_SuperApp",
    title: "QuickGrab Super App",
    description:
      "A multi-module e-commerce super app in Jetpack Compose with separate admin and customer surfaces sharing a common domain and design system.",
    url: repoUrl("QuickGrab_SuperApp"),
    language: "Kotlin",
    topics: ["multi-module", "jetpack-compose", "e-commerce", "clean-architecture"],
    stars: 0,
    forks: 0,
    category: "android",
    featured: true,
  },
  {
    id: "quickgrab-demo",
    repo: "QuickGrab-Demo",
    title: "QuickGrab",
    description:
      "Compose e-commerce reference app covering Firebase, LiveData and Flow, Room caching, Material Design and a unit-tested MVVM layer.",
    url: repoUrl("QuickGrab-Demo"),
    language: "Kotlin",
    topics: ["firebase", "mvvm", "room", "material-design", "unit-testing"],
    stars: 0,
    forks: 0,
    category: "android",
    featured: false,
  },
  {
    id: "animated-flip-view",
    repo: "AnimatedFlipView",
    title: "AnimatedFlipView",
    description:
      "A reusable Android library exposing a custom view that flips its faces with configurable animation — published as a drop-in dependency.",
    url: repoUrl("AnimatedFlipView"),
    language: "Kotlin",
    topics: ["android-library", "custom-view", "animation"],
    stars: 0,
    forks: 0,
    category: "android",
    featured: false,
  },
  {
    id: "healthucate",
    repo: "Healthucate",
    title: "Healthucate",
    description:
      "A health and fitness Android app in Java — my most-starred repository, with tracking, guidance content and a hand-built Material UI.",
    url: repoUrl("Healthucate"),
    language: "Java",
    topics: ["android", "health", "material-design"],
    stars: 4,
    forks: 2,
    category: "android",
    featured: true,
  },
  {
    id: "firebase-maestro",
    repo: "Android_Firebase_Maestro",
    title: "Android Firebase Maestro",
    description:
      "A working reference for the full Firebase surface: auth, Firestore, Realtime Database, push notifications, deep links and Crashlytics.",
    url: repoUrl("Android_Firebase_Maestro"),
    language: "Kotlin",
    topics: ["firebase", "authentication", "firestore", "crashlytics", "deep-links"],
    stars: 0,
    forks: 0,
    category: "android",
    featured: false,
  },
  {
    id: "compose-navigation",
    repo: "Jetpack_Compose_Navigation",
    title: "Compose Navigation Deep Dive",
    description:
      "Navigation in Compose from first principles through nested graphs, bottom-bar hosts and lifecycle-safe state retention.",
    url: repoUrl("Jetpack_Compose_Navigation"),
    language: "Kotlin",
    topics: ["jetpack-compose", "navigation", "nested-navigation"],
    stars: 0,
    forks: 0,
    category: "android",
    featured: false,
  },

  // ── Cross-Platform ────────────────────────────────────────────────────
  {
    id: "easy-keep",
    repo: "Easy-Keep",
    title: "Easy Keep",
    description:
      "A notes and task-scheduling app on Compose Multiplatform, running from one Kotlin codebase on both Android and iOS with Koin and DataStore.",
    url: repoUrl("Easy-Keep"),
    language: "Kotlin",
    topics: ["compose-multiplatform", "kmp", "koin", "datastore", "ios"],
    stars: 0,
    forks: 0,
    category: "cross-platform",
    featured: true,
  },
  {
    id: "flutter-bloc-clean",
    repo: "Flutter_Bloc_Clean_Architecture_Masterclass",
    title: "Flutter BLoC + Clean Architecture",
    description:
      "The architecture I brought to BDTICKETS, distilled: BLoC state management over strict presentation/domain/data layering with get_it, freezed and SOLID boundaries.",
    url: repoUrl("Flutter_Bloc_Clean_Architecture_Masterclass"),
    language: "Dart",
    topics: ["flutter", "bloc", "clean-architecture", "get-it", "freezed", "solid"],
    stars: 0,
    forks: 0,
    category: "cross-platform",
    featured: true,
  },
  {
    id: "flutter-ultimate",
    repo: "flutter_ultimate",
    title: "Flutter Ultimate",
    description:
      "A running reference project consolidating the Flutter patterns I reach for most — layout, state, navigation and platform integration.",
    url: repoUrl("flutter_ultimate"),
    language: "Dart",
    topics: ["flutter", "dart"],
    stars: 0,
    forks: 0,
    category: "cross-platform",
    featured: false,
  },
  {
    id: "flutter-getx-mvvm",
    repo: "Flutter_GetX_MVVM_Masterclass",
    title: "Flutter GetX + MVVM",
    description:
      "The GetX and MVVM stack behind Baby Shop — reactive controllers, a repository layer, routing and persisted preferences.",
    url: repoUrl("Flutter_GetX_MVVM_Masterclass"),
    language: "Dart",
    topics: ["flutter", "getx", "mvvm", "repository-pattern"],
    stars: 0,
    forks: 0,
    category: "cross-platform",
    featured: false,
  },
  {
    id: "easy-task",
    repo: "Easy_Task",
    title: "Easy Task",
    description:
      "A cross-platform task manager for Android and iOS with local-first Hive persistence and async-heavy scheduling logic.",
    url: repoUrl("Easy_Task"),
    language: "Dart",
    topics: ["flutter", "hive", "async", "android-ios"],
    stars: 0,
    forks: 0,
    category: "cross-platform",
    featured: false,
  },

  // ── Backend & APIs ────────────────────────────────────────────────────
  {
    id: "smart-ummah-api",
    repo: "SmartUmmah_API",
    title: "Smart Ummah API",
    description:
      "The Go service powering Smart Ummah — Fiber HTTP layer, GORM over PostgreSQL and a Docker Compose deployment.",
    url: repoUrl("SmartUmmah_API"),
    language: "Go",
    topics: ["golang", "go-fiber", "gorm", "postgresql", "docker-compose", "rest-api"],
    stars: 0,
    forks: 0,
    category: "backend",
    featured: true,
  },
  {
    id: "customer-management",
    repo: "Customer_Management_System",
    title: "Customer Management System",
    description:
      "A Spring Boot 3 service with JPA/Hibernate persistence on PostgreSQL, constructor injection throughout and a containerised runtime.",
    url: repoUrl("Customer_Management_System"),
    language: "Java",
    topics: ["spring-boot-3", "jpa-hibernate", "postgresql", "docker-compose"],
    stars: 0,
    forks: 0,
    category: "backend",
    featured: true,
  },
  {
    id: "user-management-api",
    repo: "User_Management_API",
    title: "User Management API",
    description:
      "A Spring Boot user-management API built on Spring Data JPA and JDBC against PostgreSQL, with layered service boundaries.",
    url: repoUrl("User_Management_API"),
    language: "Java",
    topics: ["spring-boot", "spring-data-jpa", "jdbc", "postgresql"],
    stars: 0,
    forks: 0,
    category: "backend",
    featured: false,
  },
  {
    id: "spring-oauth2",
    repo: "Spring_OAuth2",
    title: "Spring OAuth2",
    description:
      "Federated sign-in with Spring Security — OAuth2 authorisation-code flows for both GitHub and Google identity providers.",
    url: repoUrl("Spring_OAuth2"),
    language: "Java",
    topics: ["spring-security", "oauth2", "google-login", "github-login"],
    stars: 0,
    forks: 0,
    category: "backend",
    featured: false,
  },
  {
    id: "easy-keep-api",
    repo: "Easy-Keep_API",
    title: "Easy Keep API",
    description:
      "The REST backend for Easy Keep: Go with Gorilla Mux, MongoDB persistence and a Docker Compose stack.",
    url: repoUrl("Easy-Keep_API"),
    language: "Go",
    topics: ["golang", "gorilla-mux", "mongodb", "rest-api", "docker-compose"],
    stars: 0,
    forks: 0,
    category: "backend",
    featured: false,
  },
  {
    id: "mywallet",
    repo: "MyWallet-A_Smart_Banking_System",
    title: "MyWallet Banking System",
    description:
      "A Go banking service covering accounts, transfers and transaction history over MongoDB, exposed as a containerised REST API.",
    url: repoUrl("MyWallet-A_Smart_Banking_System"),
    language: "Go",
    topics: ["golang", "gorilla-mux", "mongodb", "rest-api"],
    stars: 0,
    forks: 0,
    category: "backend",
    featured: false,
  },

  // ── Engineering Craft ─────────────────────────────────────────────────
  {
    id: "room-hilt-testing",
    repo: "Android_Room_Hilt_Flow_Unit_Testing",
    title: "Testing Room, Hilt & Flow",
    description:
      "How I test the data layer: JUnit unit tests, Hilt test graphs, Turbine for Flow assertions and instrumented Room verification.",
    url: repoUrl("Android_Room_Hilt_Flow_Unit_Testing"),
    language: "Kotlin",
    topics: ["unit-testing", "turbine", "hilt", "room", "junit"],
    stars: 0,
    forks: 0,
    category: "engineering",
    featured: true,
  },
  {
    id: "mvvm-testing",
    repo: "Android_MVVM_Unit_Testing",
    title: "Testing MVVM",
    description:
      "ViewModel and repository testing with Mockito, MockWebServer for network contracts and Espresso for instrumentation.",
    url: repoUrl("Android_MVVM_Unit_Testing"),
    language: "Kotlin",
    topics: ["mockito", "mock-webserver", "espresso", "instrumentation-tests"],
    stars: 0,
    forks: 0,
    category: "engineering",
    featured: false,
  },
  {
    id: "problem-solving-pro",
    repo: "Problem_Solving_Pro",
    title: "Problem Solving Pro",
    description:
      "503+ solved problems across LeetCode, CodeChef, HackerRank, Toph and GeeksForGeeks, organised by data structure and technique.",
    url: repoUrl("Problem_Solving_Pro"),
    language: "Java",
    topics: ["data-structures", "algorithms", "leetcode", "optimization"],
    stars: 0,
    forks: 0,
    category: "engineering",
    featured: true,
  },
  {
    id: "ocular-diseases",
    repo: "Ocular_Diseases_Detection_Using_Deep_Learning",
    title: "Ocular Disease Detection",
    description:
      "A PyTorch convolutional network that classifies multiple eye diseases from retinal imagery — my undergraduate deep-learning research.",
    url: repoUrl("Ocular_Diseases_Detection_Using_Deep_Learning"),
    language: "Jupyter Notebook",
    topics: ["deep-learning", "pytorch", "cnn", "image-processing"],
    stars: 0,
    forks: 1,
    category: "engineering",
    featured: true,
  },
] as const;

export const GITHUB_PROFILE = {
  username: GITHUB_USER,
  url: `https://github.com/${GITHUB_USER}`,
  publicRepos: 123,
  originalRepos: 84,
} as const;
